# Generated by Django 5.0.6 on 2026-06-17 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empunhadura',
                'verbose_name_plural': 'Empunhaduras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Handedness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mão Dominante',
                'verbose_name_plural': 'Mãos Dominantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Atleta',
                'verbose_name_plural': 'Tipos de Atletas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('blade_type', models.CharField(choices=[('OFF', 'Ofensiva'), ('DEF', 'Defensiva'), ('ALL', 'All-Round'), ('CAR', 'Carbono'), ('COM', 'Compósita')], default='ALL', max_length=3, verbose_name='Tipo')),
                ('speed_class', models.CharField(choices=[('SLOW', 'Lenta'), ('MED', 'Média'), ('FAST', 'Rápida'), ('VFAST', 'Muito Rápida')], default='MED', max_length=5, verbose_name='Classe de Velocidade')),
                ('weight', models.CharField(blank=True, max_length=20, verbose_name='Peso')),
                ('layers', models.IntegerField(blank=True, null=True, verbose_name='Número de Camadas')),
                ('handle', models.CharField(blank=True, max_length=50, verbose_name='Cabo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blades_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Madeira',
                'verbose_name_plural': 'Madeiras',
                'ordering': ['brand', 'name'],
                'unique_together': {('name', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='Rubber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('category', models.CharField(choices=[('TACKY', 'Adesiva'), ('TENSOR', 'Tensor'), ('HYBRID', 'Híbrida'), ('ANTI', 'Anti'), ('CLASSIC', 'Clássica')], default='TENSOR', max_length=10, verbose_name='Categoria')),
                ('rubber_type', models.CharField(choices=[('FH', 'Forehand'), ('BH', 'Backhand'), ('UNI', 'Universal')], default='UNI', max_length=3, verbose_name='Tipo')),
                ('thickness', models.CharField(blank=True, max_length=20, verbose_name='Espessura')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Cor')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rubbers_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Borracha',
                'verbose_name_plural': 'Borrachas',
                'ordering': ['brand', 'name'],
                'unique_together': {('name', 'brand')},
            },
        ),
    ]
