# Generated by Django 5.0.6 on 2026-06-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('COACH', 'Técnico'), ('ATHLETE', 'Atleta'), ('ANALYST', 'Analista')], default='ATHLETE', max_length=10, verbose_name='Tipo de Usuário'),
        ),
    ]
