# Generated by Django 5.0.6 on 2026-06-16 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('users', '0003_profile_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Aprovação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10, verbose_name='Status da Aprovação'),
        ),
        migrations.AddField(
            model_name='profile',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clubs.club', verbose_name='Clube'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revisado em'),
        ),
        migrations.AddField(
            model_name='profile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
    ]
