# Generated by Django 5.0.6 on 2026-06-16 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Aprovação'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=10, verbose_name='Status da Aprovação'),
        ),
        migrations.AddField(
            model_name='club',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da rejeição'),
        ),
        migrations.AddField(
            model_name='club',
            name='requested_by',
            field=models.ForeignKey(limit_choices_to={'profile__user_type': 'COACH'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='club',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revisado em'),
        ),
        migrations.AddField(
            model_name='club',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Revisado por'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/logos/%Y/%m/', verbose_name='Logo'),
        ),
    ]
